# Configuration file for fast_fake_rest program
# File name: config.yaml
# Location: /usr/local/etc/fast_fake_rest
###############################################

# TCP port
TcpPort: 8083

# Debug level
DebugLevel: debug

# Allow logging to console
ConsoleLogging: true

# Allow logging to file
FileLogging: true

# Log files path
LogFilesPath: /var/log/fast_fake_rest

# REST
rest:
  - EndPoint: /v1/endpoint1
    Response: '{response1: "1111111"}'

  - EndPoint: /v1/endpoint2
    Response: '{response2: "2222222"}'

  - EndPoint: /v1/endpoint3
    Response: '{response3: "3333333"}'
